manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: geeksville
      url-base: https://github.com/geeksville
    - name: beekeeb
      url-base: https://github.com/beekeeb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk_driver_azoteq
      remote: geeksville
      revision: master
    - name: zmk-input-zoom
      remote: beekeeb
      revision: main
  self:
    path: config
